export const ROUTES = {
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  dashboard: '/dashboard',
  formations: '/formations',
  formationsCreate: '/formations/create',
  formationsEdit: (id: number) => `/formations/${id}/edit`,
  formationsDetail: (id: number) => `/formations/${id}`,
  students: '/students',
  studentsDetail: (id: number) => `/students/${id}`,
  enrollments: '/enrollments',
  enrollmentsDetail: (id: number) => `/enrollments/${id}`,
  myCourses: '/my-courses',
  coursePlayer: (enrollmentId: number) => `/my-courses/${enrollmentId}/play`,
  profile: '/profile',
  profileEdit: '/profile/edit',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminFormations: '/admin/formations',
  adminStatistics: '/admin/statistics',
  notFound: '/404',
  serverError: '/500',
} as const;
