export const ROUTE_PATHS = {
  login: 'login',
  register: 'register',
  forgotPassword: 'forgot-password',
  dashboard: 'dashboard',
  formations: 'formations',
  formationsCreate: 'create',
  formationsEdit: 'edit',
  formationsDetail: ':id',
  students: 'students',
  studentsDetail: ':id',
  enrollments: 'enrollments',
  enrollmentsDetail: ':id',
  myCourses: 'my-courses',
  coursePlayer: ':enrollmentId/play',
  profile: 'profile',
  profileEdit: 'edit',
  admin: 'admin',
  adminUsers: 'users',
  adminFormations: 'formations',
  adminStatistics: 'statistics',
  notFound: '404',
  serverError: '500',
} as const;
